Checking out grappelli from git+git:https://github.com/bryanveloso/django-grappelli#egg=grappelli checkout from git+git:https://github.com/bryanveloso/django-grappelli#egg=grappelli
  Cloning git:///https://github.com/bryanveloso/django-grappelli to ./src/grappelli
  Running command git clone -q git:///https://github.com/bryanveloso/django-grappelli /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli
  Complete output from command git clone -q git:///https://github.com/bryanveloso/django-grappelli /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli:
  
----------------------------------------
Command git clone -q git:///https://github.com/bryanveloso/django-grappelli /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli failed with error code 128
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1741, in install_files
    req_to_install.update_editable()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1486, in update_editable
    version_control(self.url).obtain(self.source_dir)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 2804, in obtain
    [GIT_CMD, 'clone', '-q', url, dest])
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command git clone -q git:///https://github.com/bryanveloso/django-grappelli /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli failed with error code 128
------------------------------------------------------------
/usr/bin/pip run on Fri Jul 15 10:06:15 2011
Checking out grappelli from git+git:https://github.com/bryanveloso/django-grappelli#egg=grappelli checkout from git+git:https://github.com/bryanveloso/django-grappelli#egg=grappelli
  Cloning git:///https://github.com/bryanveloso/django-grappelli to ./src/grappelli
  Running command git clone -q git:///https://github.com/bryanveloso/django-grappelli /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli
  Complete output from command git clone -q git:///https://github.com/bryanveloso/django-grappelli /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli:
  
----------------------------------------
Command git clone -q git:///https://github.com/bryanveloso/django-grappelli /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli failed with error code 128
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1741, in install_files
    req_to_install.update_editable()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1486, in update_editable
    version_control(self.url).obtain(self.source_dir)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 2804, in obtain
    [GIT_CMD, 'clone', '-q', url, dest])
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command git clone -q git:///https://github.com/bryanveloso/django-grappelli /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli failed with error code 128
------------------------------------------------------------
/usr/bin/pip run on Fri Jul 15 10:07:03 2011
Checking out grappelli from git+git:https://github.com/bryanveloso/django-grappelli.git#egg=grappelli checkout from git+git:https://github.com/bryanveloso/django-grappelli.git#egg=grappelli
  Cloning git:///https://github.com/bryanveloso/django-grappelli.git to ./src/grappelli
  Running command git clone -q git:///https://github.com/bryanveloso/django-grappelli.git /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli
  Complete output from command git clone -q git:///https://github.com/bryanveloso/django-grappelli.git /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli:
  
----------------------------------------
Command git clone -q git:///https://github.com/bryanveloso/django-grappelli.git /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli failed with error code 128
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1741, in install_files
    req_to_install.update_editable()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1486, in update_editable
    version_control(self.url).obtain(self.source_dir)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 2804, in obtain
    [GIT_CMD, 'clone', '-q', url, dest])
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command git clone -q git:///https://github.com/bryanveloso/django-grappelli.git /home/shopifyplus/webapps/alpha.shopifyplus/shopifyplus/src/grappelli failed with error code 128
